name: Auto Deploy Backend to VPS

on:
  push:
    branches:
      - DEV  # Ganti dengan branch deploy kamu

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Deploy via SSH to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /opt/test-deploy-be/express-template-be
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          debug: true